/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Metier.Film;
import javax.swing.JOptionPane;
import Model.ModeleComboBoxGenre;

/**
 *
 * @author Claire et louis
 */
public class FenetreSaisieFilm extends javax.swing.JDialog {

    private Film film;
    private boolean etatSortie;
    private ModeleComboBoxGenre modeleComboBoxGenre;

    /**
     * Constructeur
     *
     * @param parent
     * @param film
     * @param modeleComboBoxGenre
     */
    public FenetreSaisieFilm(javax.swing.JDialog parent, Film film, ModeleComboBoxGenre modeleComboBoxGenre) {
        super(parent, true);
        this.film = film;
        etatSortie = false;
        this.modeleComboBoxGenre = modeleComboBoxGenre;

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jlbNumVIP = new javax.swing.JLabel();
        jlbNomVIP = new javax.swing.JLabel();
        jlbPrenomVIP = new javax.swing.JLabel();
        jlbCodeStatut = new javax.swing.JLabel();
        txtVisa = new javax.swing.JTextField();
        txtNomFilm = new javax.swing.JTextField();
        txtAnnee = new javax.swing.JTextField();
        jbtnSoumettre = new javax.swing.JButton();
        jcbGenre = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Saisie d'un film ");

        jlbNumVIP.setText("Numéro Visa");

        jlbNomVIP.setText("Nom film");

        jlbPrenomVIP.setText("Année sortie");

        jlbCodeStatut.setText("Genre");

        jbtnSoumettre.setText("Soumettre");
        jbtnSoumettre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSoumettreActionPerformed(evt);
            }
        });

        jcbGenre.setModel(modeleComboBoxGenre);
        jcbGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbGenreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlbNumVIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbNomVIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbPrenomVIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlbCodeStatut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVisa)
                    .addComponent(txtNomFilm)
                    .addComponent(txtAnnee)
                    .addComponent(jcbGenre, 0, 185, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jbtnSoumettre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNumVIP)
                    .addComponent(txtVisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNomVIP)
                    .addComponent(txtNomFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPrenomVIP)
                    .addComponent(txtAnnee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCodeStatut)
                    .addComponent(jcbGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnSoumettre)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSoumettreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSoumettreActionPerformed
        try {
            if (txtVisa.getText().isEmpty()) {
                throw new Exception("Champ Visa vide!");
            }
            film.setVisa(Integer.parseInt(txtVisa.getText()));
            if (txtNomFilm.getText().isEmpty()) {
                throw new Exception("Champ Titre vide!");
            }
            film.setTitre(txtNomFilm.getText());

            if (txtAnnee.getText().isEmpty()) {
                throw new Exception("Champ Annee vide!");
            }
            film.setAnnee(Integer.parseInt(txtAnnee.getText()));

            if (jcbGenre.getSelectedItem().toString().isEmpty()) {
                throw new Exception("Champ Genre vide!");
            }
            film.setGenre(jcbGenre.getSelectedItem().toString());
            etatSortie = true;
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur insertion film: " + e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_jbtnSoumettreActionPerformed

    private void jcbGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbGenreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbGenreActionPerformed

    /**
     * gestion modal
     *
     * @return
     */
    public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JButton jbtnSoumettre;
    private javax.swing.JComboBox jcbGenre;
    private javax.swing.JLabel jlbCodeStatut;
    private javax.swing.JLabel jlbNomVIP;
    private javax.swing.JLabel jlbNumVIP;
    private javax.swing.JLabel jlbPrenomVIP;
    private javax.swing.JTextField txtAnnee;
    private javax.swing.JTextField txtNomFilm;
    private javax.swing.JTextField txtVisa;
    // End of variables declaration//GEN-END:variables
}
