/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Metier.Film;
import Metier.Photo;
import Model.ModeleComboBoxGenre;
import Model.ModeleJTableFilm;
import Model.ModeleJTablePhotos;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Louis
 */
public class FenetreGestionFilm extends javax.swing.JDialog {

    private boolean etatSortie;
    private Film film;
    private ModeleJTableFilm leModeleFilm;
    private ModeleComboBoxGenre csCf;
    public FenetreGestionFilm(java.awt.Frame parent, Film film, ModeleJTableFilm leModeleFilm,ModeleComboBoxGenre csCf) {

        super(parent, true);
        this.csCf=csCf;
        this.etatSortie = false;
        this.film = film;
        this.leModeleFilm = leModeleFilm;

        initComponents();
          try {
            leModeleFilm.lireLesPhotos();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbnAjoutPhoto = new javax.swing.JButton();
        jbnSuppr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFilm = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestionnaire de Films");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbnAjoutPhoto.setText("Ajouter une photo");
        jbnAjoutPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnAjoutPhotoActionPerformed(evt);
            }
        });

        jbnSuppr.setText("Supprimer");
        jbnSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnSupprActionPerformed(evt);
            }
        });

        jTableFilm.setModel(leModeleFilm);
        jScrollPane1.setViewportView(jTableFilm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbnAjoutPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbnSuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnAjoutPhoto)
                    .addComponent(jbnSuppr))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnAjoutPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnAjoutPhotoActionPerformed
        try {
            Film leFilm = new Film();
            FenetreSaisieFilm saise = new FenetreSaisieFilm(this,leFilm,csCf);
            if (saise.doModal() == true) {
                System.out.println(leFilm.toString());
                       leModeleFilm.insererFilm(leFilm);
            }
            etatSortie=true;
            this.dispose();

        } catch (Exception e) {
            System.out.println("Erreur: " + e.getMessage());
        }

    }//GEN-LAST:event_jbnAjoutPhotoActionPerformed

    private void jbnSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnSupprActionPerformed
         try {
            int ligne = jTableFilm.getSelectedRow();
            leModeleFilm.supprimerFilm(ligne);
        } catch (Exception e) {
            System.out.println("Exception à la suppression : " + e.getMessage());
        }
    }//GEN-LAST:event_jbnSupprActionPerformed

    /**
     * @param args the command line arguments
     */
    public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFilm;
    private javax.swing.JButton jbnAjoutPhoto;
    private javax.swing.JButton jbnSuppr;
    // End of variables declaration//GEN-END:variables
}
