/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Metier.Photo;
import java.io.File;
import java.sql.Date;

/**
 *
 * @author Louis
 */
public class FenetreUploadPhoto extends javax.swing.JDialog {

    private boolean etatSortie;
    private Photo laPhoto;

    public FenetreUploadPhoto(javax.swing.JDialog parent, Photo laPhoto) {
        super(parent, true);
        this.etatSortie = false;
        this.laPhoto = laPhoto;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jfcPhoto = new javax.swing.JFileChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtIdVip = new javax.swing.JTextField();
        jtxtDatePhoto = new javax.swing.JTextField();
        jtxtLieuPhoto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Uploader une photo");

        jfcPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfcPhotoActionPerformed(evt);
            }
        });

        jLabel2.setText("IdVip:");

        jLabel4.setText("Date photo:");

        jLabel5.setText("Lieu photo:");

        jtxtIdVip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIdVipActionPerformed(evt);
            }
        });

        jtxtDatePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDatePhotoActionPerformed(evt);
            }
        });

        jtxtLieuPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLieuPhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtIdVip)
                            .addComponent(jtxtDatePhoto)
                            .addComponent(jtxtLieuPhoto))
                        .addGap(18, 18, 18)
                        .addComponent(jfcPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfcPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtIdVip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDatePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtLieuPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfcPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfcPhotoActionPerformed
        try {
            File f = jfcPhoto.getSelectedFile();
            laPhoto.setIdPhoto(f.getName());
            laPhoto.setLien(f.getAbsolutePath());
             if (jtxtIdVip.getText().isEmpty()) {
                throw new Exception("Champs IdVip vide!");
            }
            laPhoto.setIdVip(Integer.parseInt(jtxtIdVip.getText()));
            if (jtxtDatePhoto.getText().isEmpty()) {
                throw new Exception("Champs Date vide!");
            }
            laPhoto.setLaDate(Date.valueOf(jtxtDatePhoto.getText()));
            if (jtxtLieuPhoto.getText().isEmpty()) {
                throw new Exception("Champs Lieu vide!");
            }
            laPhoto.setLieu(jtxtLieuPhoto.getText());
            etatSortie=true;
            this.dispose();
        } catch (Exception e) {
            System.out.println("Erreur: " + e.getMessage());
        }

    }//GEN-LAST:event_jfcPhotoActionPerformed

    private void jtxtIdVipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIdVipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIdVipActionPerformed

    private void jtxtDatePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDatePhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDatePhotoActionPerformed

    private void jtxtLieuPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLieuPhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLieuPhotoActionPerformed

    public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JFileChooser jfcPhoto;
    private javax.swing.JTextField jtxtDatePhoto;
    private javax.swing.JTextField jtxtIdVip;
    private javax.swing.JTextField jtxtLieuPhoto;
    // End of variables declaration//GEN-END:variables
}
