/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Metier.Casting;
import Metier.Film;
import Metier.Photo;
import Metier.Real;
import Model.ModeleComboBoxFilm;
import Model.ModeleComboBoxGenre;
import Model.ModeleComboBoxVIPAct;
import Model.ModeleComboBoxVIPReal;
import Model.ModeleJTableFilm;
import Model.ModeleJTablePhotos;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Louis
 */
public class FenetreGestionFilm extends javax.swing.JDialog {

    private boolean etatSortie;
    private Film film;
    private ModeleJTableFilm leModeleFilm;
    private ModeleComboBoxGenre csCf;
    private ModeleComboBoxFilm CBVF;
    private ModeleComboBoxVIPAct CBVA;
    private ModeleComboBoxVIPReal CBVR;
    public FenetreGestionFilm(java.awt.Frame parent,  ModeleJTableFilm leModeleFilm,ModeleComboBoxGenre csCf,ModeleComboBoxFilm CBVF,ModeleComboBoxVIPAct CBVA,ModeleComboBoxVIPReal CBVR) {

        super(parent, true);
        this.csCf=csCf;
         this.CBVF=CBVF;     
this.CBVA=CBVA;
this.CBVR=CBVR;
        this.etatSortie = false;
        //this.film = film;
        this.leModeleFilm = leModeleFilm;

        initComponents();
          try {
            leModeleFilm.lireLesFilm();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            Logger.getLogger(FenetreApplication.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jbnAjoutPhoto = new javax.swing.JButton();
        jbnSuppr = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFilm = new javax.swing.JTable();
        jBCast = new javax.swing.JButton();
        jBReal = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestionnaire de Films");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbnAjoutPhoto.setText("Ajouter un film");
        jbnAjoutPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnAjoutPhotoActionPerformed(evt);
            }
        });

        jbnSuppr.setText("Supprimer");
        jbnSuppr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnSupprActionPerformed(evt);
            }
        });

        jTableFilm.setModel(leModeleFilm);
        jScrollPane1.setViewportView(jTableFilm);

        jBCast.setText("Gestion Casting");
        jBCast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCastActionPerformed(evt);
            }
        });

        jBReal.setText("Gestion Realisation");
        jBReal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbnAjoutPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbnSuppr, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBReal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBCast, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jBCast)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBReal)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnAjoutPhoto)
                    .addComponent(jbnSuppr))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnAjoutPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnAjoutPhotoActionPerformed
        try {
            Film leFilm = new Film();
            FenetreSaisieFilm saise = new FenetreSaisieFilm(this,leFilm,csCf);
            if (saise.doModal() == true) {
                System.out.println(leFilm.toString());
                       leModeleFilm.insererFilm(leFilm);
            }
          //  etatSortie=true;
         //  this.dispose();

        } catch (Exception e) {
            System.out.println("Erreur : " + e.getMessage());
        }

    }//GEN-LAST:event_jbnAjoutPhotoActionPerformed

    private void jbnSupprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnSupprActionPerformed
         try {
            int ligne = jTableFilm.getSelectedRow();
            leModeleFilm.supprimerFilm(ligne);
        } catch (Exception e) {
            System.out.println("Exception à la suppression : " + e.getMessage());
        }
    }//GEN-LAST:event_jbnSupprActionPerformed

    private void jBCastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCastActionPerformed
         try {
             int ligne = jTableFilm.getSelectedRow();
            Casting cas = new Casting();
            FenetreCasting saise = new FenetreCasting(this,cas,leModeleFilm.getValueAt(ligne,1).toString(),Integer.parseInt(leModeleFilm.getValueAt(ligne,0).toString()),CBVA,CBVF);
            if (saise.doModal() == true) {
                //System.out.println(leFilm.toString());
                      //CBVF.insererCast(cas);
            }
         //   etatSortie=true;
          // this.dispose();

        } catch (Exception e) {
            System.out.println("Erreur : " + e.getMessage());
        }
    }//GEN-LAST:event_jBCastActionPerformed

    private void jBRealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRealActionPerformed
        try {
                 int ligne = jTableFilm.getSelectedRow();
            Real real = new Real();
            FenetreReal saise = new FenetreReal(this,real,leModeleFilm.getValueAt(ligne,1).toString(),Integer.parseInt(leModeleFilm.getValueAt(ligne,0).toString()),CBVF,CBVR);
            if (saise.doModal() == true) {
                //System.out.println(leFilm.toString());
                       CBVF.insererReal(real);
            }
         //   etatSortie=true;
          // this.dispose();

        } catch (Exception e) {
            System.out.println("Erreur : " + e.getMessage());
        }
    }//GEN-LAST:event_jBRealActionPerformed

    /**
     * @param args the command line arguments
     */
    public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCast;
    private javax.swing.JButton jBReal;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFilm;
    private javax.swing.JButton jbnAjoutPhoto;
    private javax.swing.JButton jbnSuppr;
    // End of variables declaration//GEN-END:variables
}
