/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import Metier.Casting;
import Metier.VIP;
import javax.swing.JOptionPane;
import Model.ModeleComboBoxFilm;
import Model.ModeleComboBoxVIPAct;

public class FenetreCasting extends javax.swing.JDialog {

    private Casting casting;
    private boolean etatSortie;
    private ModeleComboBoxFilm modeleComboBoxFilms;
    private String nomFilm;
    private int numVisa;
    private ModeleComboBoxVIPAct modeleComboBoxActeur;

    /**
     * Constructeur
     *
     * @param parent
     * @param casting
     * @param nomFilm
     * @param numVisa
     * @param modeleComboBoxActeur
     * @param modeleComboBoxFilms
     */
    public FenetreCasting(javax.swing.JDialog parent, Casting casting, String nomFilm, int numVisa, ModeleComboBoxVIPAct modeleComboBoxActeur, ModeleComboBoxFilm modeleComboBoxFilms) {
        super(parent, true);
        this.casting = casting;
        etatSortie = false;
        this.modeleComboBoxActeur = modeleComboBoxActeur;
        this.numVisa = numVisa;
        this.nomFilm = nomFilm;
        this.modeleComboBoxFilms = modeleComboBoxFilms;

        initComponents();

        jlblNomFilm.setText(nomFilm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbNomVIP = new javax.swing.JLabel();
        jlbPrenomVIP = new javax.swing.JLabel();
        jbtnSoumettre = new javax.swing.JButton();
        jcbAct = new javax.swing.JComboBox();
        jlblNomFilm = new javax.swing.JTextField();
        jbtnQuitter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Saisie d'un VIP");

        jlbNomVIP.setText("Film");

        jlbPrenomVIP.setText("Acteur");

        jbtnSoumettre.setText("Ajouter l'acteur");
        jbtnSoumettre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSoumettreActionPerformed(evt);
            }
        });

        jcbAct.setModel(modeleComboBoxActeur);

        jlblNomFilm.setEditable(false);

        jbtnQuitter.setText("Quitter");
        jbtnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnQuitterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbNomVIP, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jlblNomFilm)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnSoumettre)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbAct, 0, 192, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbPrenomVIP, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNomVIP)
                    .addComponent(jlbPrenomVIP))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblNomFilm)
                        .addGap(2, 2, 2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnSoumettre)
                    .addComponent(jbtnQuitter))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSoumettreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSoumettreActionPerformed
        try {
            //recuperation des champ et mis a jour de l'objet cas
            casting.setNumVisa(numVisa);
            if (jcbAct.getSelectedItem().toString().isEmpty()) {
                throw new Exception("acteur");
            }
            casting.setIdVip(((VIP) jcbAct.getSelectedItem()).getIdVip());
            modeleComboBoxFilms.insererCast(casting);
            modeleComboBoxActeur.setSelectedItem(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur insertion casting: " + e.getMessage(), "Erreur", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_jbtnSoumettreActionPerformed

    private void jbtnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnQuitterActionPerformed
        etatSortie = true;
        this.dispose();

    }//GEN-LAST:event_jbtnQuitterActionPerformed

    /**
     *
     * @return
     */
    public boolean doModal() {
        setVisible(true);
        return etatSortie;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnQuitter;
    private javax.swing.JButton jbtnSoumettre;
    private javax.swing.JComboBox jcbAct;
    private javax.swing.JLabel jlbNomVIP;
    private javax.swing.JLabel jlbPrenomVIP;
    private javax.swing.JTextField jlblNomFilm;
    // End of variables declaration//GEN-END:variables
}
